name: Print Secret on Push

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print API_KEY Secret
        run: echo "API_KEY=${{ secrets.API_KEY }}"

